# Site settings
title: Davis Kirkendall
email: davis.kirkendall@rwth-aachen.de
description: My personal coding blog, describing problems, solutions and generally interesting stuff I come across while working on my projects which in include advanced fluid mechanics, data analysis and large scale optimization
algorithms. baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://daviskirk.github.io" # the base hostname & protocol for your site
exclude: [Gemfile, Gemfile.lock, org, .git, .gitignore]
# Build settings
markdown: kramdown

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: false
github_username: daviskirk
stackoverflow_id:
twitter_username:
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
# markdown: redcarpet
redcarpet:
extensions: ['smart', 'tables', 'with_toc_data']
permalink: pretty
paginate: 3
sass:
compressed: true
