# Site settings
title: Davis Kirkendall
email: davis.kirkendall@rwth-aachen.de
description: My personal coding blog, describing problems, solutions and generally interesting stuff I come across while working on my projects which in include advanced fluid mechanics, data analysis and large scale optimization
algorithms. baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://daviskirk.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  daviskirk
exclude: [Gemfile, Gemfile.lock, org, .git, .gitignore]
# Build settings
markdown: kramdown
